# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_in_stock', models.PositiveIntegerField(default=0, verbose_name='unidades en inventario')),
                ('reorder_level', models.PositiveIntegerField(default=0, verbose_name='nivel de reorden')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
                'ordering': ['product__description'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(verbose_name='cambio (+/-)')),
                ('reason', models.CharField(choices=[('SALE_PAID', 'Venta pagada (mini app)'), ('MANUAL', 'Ajuste manual'), ('RETURN', 'Devolucion / logistica inversa'), ('INITIAL', 'Carga inicial')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Ej. numero de pago o pedido relacionado', max_length=120, verbose_name='referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
