# Generated by Django 5.1.4 on 2026-07-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toka_user_id', models.CharField(db_index=True, max_length=64, verbose_name='userId Toka')),
                ('toka_access_token', models.TextField(blank=True, verbose_name='accessToken Toka')),
                ('toka_access_expiry', models.DateTimeField(blank=True, null=True, verbose_name='expira accessToken')),
                ('toka_refresh_token', models.TextField(blank=True, verbose_name='refreshToken Toka')),
                ('toka_refresh_expiry', models.DateTimeField(blank=True, null=True, verbose_name='expira refreshToken')),
                ('granted_scopes', models.JSONField(blank=True, default=list, verbose_name='scopes autorizados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='miniapp_session', to='orders.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'sesion mini-app',
                'verbose_name_plural': 'sesiones mini-app',
            },
        ),
    ]
