# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('width', models.PositiveIntegerField(default=1080, verbose_name='ancho (px)')),
                ('height', models.PositiveIntegerField(default=1080, verbose_name='alto (px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'carrusel',
                'verbose_name_plural': 'carruseles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/carousel/', verbose_name='imagen')),
                ('link_url', models.URLField(blank=True, verbose_name='url de destino')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='posicion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.carousel')),
            ],
            options={
                'verbose_name': 'imagen de carrusel',
                'verbose_name_plural': 'imagenes de carrusel',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
