# Generated by Django 5.1.4 on 2026-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='height',
            field=models.PositiveIntegerField(default=192, verbose_name='alto (px)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='width',
            field=models.PositiveIntegerField(default=330, verbose_name='ancho (px)'),
        ),
    ]
