# Generated by Django 5.1.4 on 2026-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_carousel_height_alter_carousel_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='height',
            field=models.PositiveIntegerField(default=440, verbose_name='alto (px)'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='width',
            field=models.PositiveIntegerField(default=1380, verbose_name='ancho (px)'),
        ),
    ]
