# Generated by Django 5.1.4 on 2026-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_carousel_height_alter_carousel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, help_text='Id de la categoria, marca o producto al que navega el tap.', null=True, verbose_name='id de destino'),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='target_type',
            field=models.CharField(blank=True, choices=[('CATEGORY', 'Categoria'), ('BRAND', 'Marca'), ('PRODUCT', 'Producto')], default='', max_length=10, verbose_name='tipo de destino'),
        ),
    ]
