# Generated by Django 5.1.4 on 2026-08-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_carouselimage_target_id_carouselimage_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activar desde'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='desactivar el'),
        ),
    ]
