# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toka_customer_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID cliente Toka')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('contact_number', models.CharField(blank=True, max_length=30, verbose_name='numero de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Ej. Casa, Oficina', max_length=60, verbose_name='etiqueta')),
                ('full_address', models.CharField(max_length=255, verbose_name='direccion completa')),
                ('address_complement', models.CharField(blank=True, max_length=255, verbose_name='complemento de direccion')),
                ('colonia', models.CharField(max_length=120, verbose_name='colonia')),
                ('city_alcaldia', models.CharField(max_length=120, verbose_name='ciudad / alcaldia')),
                ('state', models.CharField(max_length=120, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='codigo postal')),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'direccion de cliente',
                'verbose_name_plural': 'direcciones de clientes',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('contact_number', models.CharField(blank=True, max_length=30, verbose_name='numero de contacto')),
                ('full_address', models.CharField(max_length=255, verbose_name='direccion completa')),
                ('address_complement', models.CharField(blank=True, max_length=255, verbose_name='complemento de direccion')),
                ('colonia', models.CharField(max_length=120, verbose_name='colonia')),
                ('city_alcaldia', models.CharField(max_length=120, verbose_name='ciudad / alcaldia')),
                ('state', models.CharField(max_length=120, verbose_name='estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='codigo postal')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de pago'), ('PAID', 'Pagado'), ('PREPARING', 'En preparacion'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto total')),
                ('stock_deducted', models.BooleanField(default=False, help_text='True una vez que el pago fue confirmado y se descuento inventario.', verbose_name='stock descontado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
                ('saved_address', models.ForeignKey(blank=True, help_text='Direccion guardada seleccionada por el cliente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customeraddress')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'linea de pedido',
                'verbose_name_plural': 'lineas de pedido',
            },
        ),
    ]
