# Generated by Django 5.1.4 on 2026-07-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=30, verbose_name='numero de contacto'),
        ),
    ]
