# Generated by Django 5.1.4 on 2026-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='address_complement',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='city_alcaldia',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='complete_address',
            field=models.CharField(default='', max_length=255, verbose_name='direccion (calle y numero)'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='custom_label',
            field=models.CharField(blank=True, default='', help_text="Se usa cuando la etiqueta es 'Otro'.", max_length=60, verbose_name='etiqueta personalizada'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='delivery_instructions',
            field=models.TextField(blank=True, default='', verbose_name='instrucciones de entrega'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='localidad'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='municipality',
            field=models.CharField(default='', max_length=120, verbose_name='municipio / alcaldia'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='no_street_number',
            field=models.BooleanField(default=False, verbose_name='sin numero'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='suburb',
            field=models.CharField(default='', max_length=120, verbose_name='colonia'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='supplementary_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='complemento (interior, referencias)'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='unknown_zip_code',
            field=models.BooleanField(default=False, verbose_name='no conoce el CP'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(choices=[('HOME', 'Casa'), ('OFFICE', 'Oficina'), ('UNIVERSITY', 'Universidad'), ('OTHER', 'Otro')], default='HOME', max_length=20, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(default='', max_length=120, verbose_name='estado'),
        ),
    ]
