# Generated by Django 5.1.4 on 2026-07-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_customeraddress_address_complement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='transportadora'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_guide',
            field=models.CharField(blank=True, default='', help_text='Numero de guia de la transportadora.', max_length=120, verbose_name='guia de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de despacho'), ('LEFT_WAREHOUSE', 'Salio de bodega'), ('IN_TRANSIT', 'En camino a WH Transport'), ('OUT_FOR_DELIVERY', 'En reparto al domicilio'), ('DELIVERED', 'Entregado'), ('EXCEPTION', 'Novedad')], default='PENDING', max_length=20, verbose_name='estado de entrega'),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de despacho'), ('LEFT_WAREHOUSE', 'Salio de bodega'), ('IN_TRANSIT', 'En camino a WH Transport'), ('OUT_FOR_DELIVERY', 'En reparto al domicilio'), ('DELIVERED', 'Entregado'), ('EXCEPTION', 'Novedad')], max_length=20, verbose_name='estado de entrega')),
                ('note', models.TextField(blank=True, default='', help_text='Detalle del paso; obligatorio describir la Novedad.', verbose_name='nota / novedad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario del back office que registro el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'evento de tracking',
                'verbose_name_plural': 'eventos de tracking',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
