# Generated by Django 5.1.4 on 2026-08-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_carrier_order_tracking_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingevent',
            name='carrier',
            field=models.CharField(blank=True, default='', help_text='Transportadora que llevaba el pedido en este paso (snapshot).', max_length=120, verbose_name='transportadora'),
        ),
    ]
