# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripcion')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SKU')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de venta')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='imagen 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='imagen 4')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['description'],
            },
        ),
    ]
