# Generated by Django 5.1.4 on 2026-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MexicoPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5, verbose_name='codigo postal')),
                ('state', models.CharField(max_length=120, verbose_name='estado')),
                ('municipality', models.CharField(max_length=150, verbose_name='municipio / alcaldia')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='ciudad / localidad')),
                ('suburb', models.CharField(max_length=200, verbose_name='colonia / asentamiento')),
                ('settlement_type', models.CharField(blank=True, max_length=80, verbose_name='tipo de asentamiento')),
            ],
            options={
                'verbose_name': 'codigo postal MX',
                'verbose_name_plural': 'codigos postales MX',
                'ordering': ['zip_code', 'suburb'],
                'indexes': [models.Index(fields=['state', 'municipality'], name='locations_m_state_9ea5ba_idx'), models.Index(fields=['zip_code', 'suburb'], name='locations_m_zip_cod_7e0e5c_idx')],
            },
        ),
    ]
