# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('APPROVED', 'Aprobada'), ('RECEIVED', 'Recibida'), ('REFUNDED', 'Reembolsada'), ('REJECTED', 'Rechazada')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'solicitud de devolucion',
                'verbose_name_plural': 'solicitudes de devolucion',
                'ordering': ['-created_at'],
            },
        ),
    ]
