# Generated by Django 5.1.4 on 2026-07-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toka_customer_id', models.CharField(db_index=True, max_length=64, verbose_name='ID cliente')),
                ('customer_name', models.CharField(max_length=200, verbose_name='nombre cliente')),
                ('payment_number', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='numero de pago')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='monto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado / Pagado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20, verbose_name='estado de pago')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload recibido')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'transaccion de pago',
                'verbose_name_plural': 'transacciones de pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
