# Generated by Django 5.1.4 on 2026-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Id de pago que devuelve Toka. Es la llave para consultar el estado del pago y para reembolsar.', max_length=80, verbose_name='paymentId de Toka'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_number',
            field=models.CharField(db_index=True, help_text='merchantTransId: nuestro id unico de la transaccion.', max_length=80, unique=True, verbose_name='numero de pago'),
        ),
    ]
