# Generated by Django 5.1.4 on 2026-07-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre del consumidor')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('key_prefix', models.CharField(db_index=True, max_length=12, verbose_name='prefijo de la clave')),
                ('hashed_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='hash de la clave')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('rate_limit_per_min', models.PositiveIntegerField(default=60, verbose_name='limite por minuto')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='ultimo uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consumidor de API',
                'verbose_name_plural': 'consumidores de API',
                'ordering': ['name'],
            },
        ),
    ]
